# -*- coding: utf-8 -*-
"""news_flow_accelerator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRV5jN3dOyZLxtXJTML6XRc6VTk2bsiV

# *Import package*
"""

!pip install pyshorteners
from pyshorteners import Shortener
from dateutil.parser import parse
from bs4 import BeautifulSoup
import pandas as pd
import requests
import datetime as dt
import re

pd.set_option('display.max_rows', None)

"""# *Get news*"""

class news_bot():
    def __init__(self, keywords):
        self.__token='NWTXp048fYtkVjxxqETQoK3IhjRZJmXqMW3QALs0yls' # token
        self.keywords = keywords

    def get_news(self, keyword):

        # empty
        title=[]
        url=[]
        source=[]
        time=[]

        # fetch news data
        period = '3d' if dt.datetime.today().weekday() == 0 else '1d'
        res = requests.get(f'https://news.google.com/search?q="{keyword}"%20when%3A{period}&hl=zh-TW&gl=TW&ceid=TW%3Azh-Hant')
        if res.status_code != 200:
            return print('error')
        content = res.content
        soup = BeautifulSoup(content, "html.parser")

        # title & url
        for item in soup.find_all("a", class_="JtKRv"):
            title.append(item.get_text())
            try:
                url.append(Shortener().tinyurl.short(item.get('href').replace('.', 'https://news.google.com', 1)))
            except:
                url.append(item.get('href').replace('.', 'https://news.google.com', 1))

        # source
        for item in soup.find_all("div", class_="vr1PYe"):
            source.append(item.get_text())

        # time
        for item in soup.find_all("div", class_="UOVeFe"):
            time.append(re.sub(r'(\b\d\b) 小時前', r'0\1 小時前', item.find("time").get_text()))

        # collect as df
        df = pd.DataFrame({
            'keyword':[keyword] * len(title),
            'title': title,
            'time': time,
            'source': source,
            'url': url,
        })

        # only relevant news
        useless_news = ['對帳單', '加權指數', '盤中焦點股', '熱門']
        df['title'] = df['title'].astype(str)
        df = df[(~df['title'].str.contains('|'.join(useless_news))) & (df['title'].str.contains(keyword.split(' ')[0]))]

        # only finance source
        relevant_source = ['中時新聞網', '工商時報', '經濟日報', '自由財經', 'Yahoo奇摩新聞', 'Anue鉅亨', 'ETtoday財經雲']
        df = df[df['source'].isin(relevant_source)]

        # return news_dataframe
        return df\
            .sort_values(by='time', ascending=True)\
            .reset_index(drop=True)

    def generate_message(self, df):
        keyword = df['keyword'][0]
        message = f'*{keyword}*\n'
        for i in range(len(df)):
            keyword = df["keyword"][i]
            title = df["title"][i]
            time = df["time"][i]
            source = df["source"][i]
            url = df["url"][i]

            message += f"\n{title}\n{time}{' | '}{source}\n{url}\n"
        return message

    def send_message(self, msg):
        headers = {
            "Authorization": f"Bearer {self.__token}",
            "Content-Type" : "application/x-www-form-urlencoded"
            }
        payload = {'message': msg}
        r = requests.post("https://notify-api.line.me/api/notify", headers = headers, params = payload)
        return r.status_code

    def send_news(self):
        for keyword in self.keywords:
            df = self.get_news(keyword)
            if not df.empty:
                msg = self.generate_message(df)
                self.send_message(msg)
bot = news_bot(
    [
    "鴻海 2317",
    "寶成 9904",
    "台泥 1101",
    "聯電 2303",
    "華碩 2357",
    "國巨 2327",
    "友達 2409",
    "旺旺集團",
    "技嘉 2376",
    "長春集團",
    "建大輪胎 2106",
    "宏達電 2498",
    "遠東新 1402",
    "台聚 1304",
    "力積電 6770",
    "九興控股",
    "星宇航空 2646",
    "長榮航空 2618",
    "中華航空 2610",
    "群創 3481",
    "億豐 8464",
]
)
bot.send_news()

bot = news_bot(
    [
    "鴻海 2317",
    "寶成 9904",
    "台泥 1101",
    "聯電 2303",
    "華碩 2357",
    "國巨 2327",
    "友達 2409",
    "旺旺集團",
    "技嘉 2376",
    "長春集團",
    "建大輪胎 2106",
    "宏達電 2498",
    "遠東新 1402",
    "台聚 1304",
    "力積電 6770",
    "九興控股",
    "星宇航空 2646",
    "長榮航空 2618",
    "中華航空 2610",
    "群創 3481",
    "億豐 8464",
]
)
bot.send_news()